/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author robert
 */
public class GUIF_AGREGAR_DOCTOR extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIF_AGREGAR_DOCTOR
     */
    public GUIF_AGREGAR_DOCTOR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_TABLA = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TXT_TELEFONO = new javax.swing.JTextField();
        TXT_CODIGO = new javax.swing.JTextField();
        TXT_DNI = new javax.swing.JTextField();
        TXT_NOMBRE = new javax.swing.JTextField();
        BTN_BUSCAR = new javax.swing.JButton();
        BTN_AÑADIR_INICIO = new javax.swing.JButton();
        BTN_ELIMINAR = new javax.swing.JButton();
        BTN_ACTUALIZAR = new javax.swing.JButton();
        CBX_SELC_ORDEN = new javax.swing.JComboBox<>();
        BTN_ORDENAR = new javax.swing.JButton();
        TXT_DIRECCION = new javax.swing.JTextField();
        BTN_AÑADIR_FINAL = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TBL_TABLA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TBL_TABLA);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 20, 870, 390));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("DATOS DE DOCTOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 6, -1, 30));

        TXT_TELEFONO.setBorder(javax.swing.BorderFactory.createTitledBorder("TELEFONO"));
        jPanel1.add(TXT_TELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 340, 50));

        TXT_CODIGO.setBorder(javax.swing.BorderFactory.createTitledBorder("CODIGO"));
        jPanel1.add(TXT_CODIGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 340, 50));

        TXT_DNI.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI"));
        jPanel1.add(TXT_DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 340, 50));

        TXT_NOMBRE.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRE"));
        jPanel1.add(TXT_NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 340, 50));

        BTN_BUSCAR.setText("BUSCAR");
        jPanel1.add(BTN_BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 348, 160, 41));

        BTN_AÑADIR_INICIO.setText("AÑADIR INCIO");
        jPanel1.add(BTN_AÑADIR_INICIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 150, 40));

        BTN_ELIMINAR.setText("ELIMINAR");
        jPanel1.add(BTN_ELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 465, 160, 40));

        BTN_ACTUALIZAR.setText("ACTUALIZAR");
        jPanel1.add(BTN_ACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 407, 160, 40));

        CBX_SELC_ORDEN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Nombre", " " }));
        CBX_SELC_ORDEN.setBorder(javax.swing.BorderFactory.createTitledBorder("Por Nombres"));
        jPanel1.add(CBX_SELC_ORDEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 209, 50));

        BTN_ORDENAR.setText("FILTRAR");
        jPanel1.add(BTN_ORDENAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 140, 50));

        TXT_DIRECCION.setBorder(javax.swing.BorderFactory.createTitledBorder("DIRECCION"));
        jPanel1.add(TXT_DIRECCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 292, 340, 50));

        BTN_AÑADIR_FINAL.setText("AÑADIR FINAL");
        BTN_AÑADIR_FINAL.setToolTipText("");
        jPanel1.add(BTN_AÑADIR_FINAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1258, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTN_ACTUALIZAR;
    public javax.swing.JButton BTN_AÑADIR_FINAL;
    public javax.swing.JButton BTN_AÑADIR_INICIO;
    public javax.swing.JButton BTN_BUSCAR;
    public javax.swing.JButton BTN_ELIMINAR;
    public javax.swing.JButton BTN_ORDENAR;
    public javax.swing.JComboBox<String> CBX_SELC_ORDEN;
    public javax.swing.JTable TBL_TABLA;
    public javax.swing.JTextField TXT_CODIGO;
    public javax.swing.JTextField TXT_DIRECCION;
    public javax.swing.JTextField TXT_DNI;
    public javax.swing.JTextField TXT_NOMBRE;
    public javax.swing.JTextField TXT_TELEFONO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
