package Vista;

/**
 *
 * @author AguidoRin
 */
public class GUIF_IMPRIMIR_HC extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmEstudiante
     */
    public GUIF_IMPRIMIR_HC() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTN_BUSCAR = new javax.swing.JButton();
        TXT_NOMBREPACIENTE = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TXTA_DETALLEHISTORIA = new javax.swing.JTextArea();
        BTN_IMPR_PDF = new javax.swing.JButton();
        TXT_DNIPACIENTE = new javax.swing.JTextField();
        BTN_IMPR_ATENPDF = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Historias Clínicas");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Sección", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Book Antiqua", 0, 14))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 12, 215, -1));

        BTN_BUSCAR.setBackground(new java.awt.Color(0, 153, 153));
        BTN_BUSCAR.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        BTN_BUSCAR.setText("BUSCAR");
        jPanel1.add(BTN_BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 150, 40));

        TXT_NOMBREPACIENTE.setBackground(new java.awt.Color(204, 255, 255));
        TXT_NOMBREPACIENTE.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TXT_NOMBREPACIENTE.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nombre del paciente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        TXT_NOMBREPACIENTE.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TXT_NOMBREPACIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_NOMBREPACIENTEActionPerformed(evt);
            }
        });
        jPanel1.add(TXT_NOMBREPACIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 180, 42));

        TXTA_DETALLEHISTORIA.setColumns(20);
        TXTA_DETALLEHISTORIA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TXTA_DETALLEHISTORIA.setRows(5);
        TXTA_DETALLEHISTORIA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DETALLES:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jScrollPane2.setViewportView(TXTA_DETALLEHISTORIA);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 810, 480));

        BTN_IMPR_PDF.setBackground(new java.awt.Color(0, 153, 153));
        BTN_IMPR_PDF.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        BTN_IMPR_PDF.setText("IMPRIMIR HISTORIA CLÍNICA PDF");
        jPanel1.add(BTN_IMPR_PDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 590, 310, 40));

        TXT_DNIPACIENTE.setBackground(new java.awt.Color(204, 255, 255));
        TXT_DNIPACIENTE.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TXT_DNIPACIENTE.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dni del paciente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        TXT_DNIPACIENTE.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TXT_DNIPACIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_DNIPACIENTEActionPerformed(evt);
            }
        });
        jPanel1.add(TXT_DNIPACIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 180, 42));

        BTN_IMPR_ATENPDF.setBackground(new java.awt.Color(0, 153, 153));
        BTN_IMPR_ATENPDF.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        BTN_IMPR_ATENPDF.setText("IMPRIMIR ATENCIONES PDF");
        jPanel1.add(BTN_IMPR_ATENPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 310, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_NOMBREPACIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_NOMBREPACIENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_NOMBREPACIENTEActionPerformed

    private void TXT_DNIPACIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_DNIPACIENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_DNIPACIENTEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTN_BUSCAR;
    public javax.swing.JButton BTN_IMPR_ATENPDF;
    public javax.swing.JButton BTN_IMPR_PDF;
    public javax.swing.JTextArea TXTA_DETALLEHISTORIA;
    public javax.swing.JTextField TXT_DNIPACIENTE;
    public javax.swing.JTextField TXT_NOMBREPACIENTE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
