/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Roberto
 */
public class GUIF_HISTORIACLINICA extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIF_PRUEBA_HISTORIA
     */
    public GUIF_HISTORIACLINICA() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Añadir_HistoriaClinica = new javax.swing.JButton();
        Ver_HistoriaClinica = new javax.swing.JButton();
        Actualizar_HistoriaClinica = new javax.swing.JButton();
        Panel_Contenido = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(900, 550));
        setRequestFocusEnabled(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Añadir_HistoriaClinica.setText("Añadir");
        jPanel2.add(Añadir_HistoriaClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 160, 40));

        Ver_HistoriaClinica.setText("Ver");
        jPanel2.add(Ver_HistoriaClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 160, 40));

        Actualizar_HistoriaClinica.setText("Actualizar");
        jPanel2.add(Actualizar_HistoriaClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 160, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 80));

        Panel_Contenido.setBackground(new java.awt.Color(204, 204, 204));
        Panel_Contenido.setMaximumSize(null);

        javax.swing.GroupLayout Panel_ContenidoLayout = new javax.swing.GroupLayout(Panel_Contenido);
        Panel_Contenido.setLayout(Panel_ContenidoLayout);
        Panel_ContenidoLayout.setHorizontalGroup(
            Panel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        Panel_ContenidoLayout.setVerticalGroup(
            Panel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel1.add(Panel_Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 900, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Actualizar_HistoriaClinica;
    public javax.swing.JButton Añadir_HistoriaClinica;
    public javax.swing.JPanel Panel_Contenido;
    public javax.swing.JButton Ver_HistoriaClinica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
