package Vista;

/**
 *
 * @author AguidoRin
 */
public class GUIF_BUSQUEDA_ESPEC extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmEstudiante
     */
    public GUIF_BUSQUEDA_ESPEC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTN_BUSCAR = new javax.swing.JButton();
        JCD_FECHA_FIN = new com.toedter.calendar.JDateChooser();
        JCD_FECHA_INICIO = new com.toedter.calendar.JDateChooser();
        CBX_SELEC_ESPEC = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        TBL_ATENCIONES = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar Atención");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Sección", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Book Antiqua", 0, 14))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 12, 215, -1));

        BTN_BUSCAR.setBackground(new java.awt.Color(0, 153, 153));
        BTN_BUSCAR.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        BTN_BUSCAR.setText("BUSCAR");
        jPanel1.add(BTN_BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 110, 40));

        JCD_FECHA_FIN.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha fin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.add(JCD_FECHA_FIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 150, 40));

        JCD_FECHA_INICIO.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha inicio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.add(JCD_FECHA_INICIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 140, 40));

        CBX_SELEC_ESPEC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBX_SELEC_ESPEC.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Especialidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.add(CBX_SELEC_ESPEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 160, 40));

        TBL_ATENCIONES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código atención", "Dni Paciente", "Fecha", "Especialidad", "Doctor", "Descripcion Atencion"
            }
        ));
        jScrollPane4.setViewportView(TBL_ATENCIONES);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 910, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTN_BUSCAR;
    public javax.swing.JComboBox<String> CBX_SELEC_ESPEC;
    public com.toedter.calendar.JDateChooser JCD_FECHA_FIN;
    public com.toedter.calendar.JDateChooser JCD_FECHA_INICIO;
    public javax.swing.JTable TBL_ATENCIONES;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}