package Vista;

/**
 *
 * @author AguidoRin
 */
public class GUIF_AGREGAR_ATENCION extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmIntClínica
     */
    public GUIF_AGREGAR_ATENCION() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_fechaNaciminetoPaciente = new javax.swing.JLabel();
        txt_dniPaciente = new javax.swing.JLabel();
        txt_nombrePaciente = new javax.swing.JLabel();
        txt_telefonoPaciente = new javax.swing.JLabel();
        txt_edadPaciente = new javax.swing.JLabel();
        txt_direccionPaciente = new javax.swing.JLabel();
        txt_generoPaciente = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CBX_SELECT_ESPEC = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTA_OBSERVACIONES = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TXTA_DIAGNOSTICO = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        TXTA_MOTIVO = new javax.swing.JTextArea();
        btn_modificarAtencion = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_buscarPaciente = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_tablaAtencion = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btn_agregarAtencion = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TXTA_TRATAMIENTO = new javax.swing.JTextArea();
        btn_limpiarAtencion = new javax.swing.JButton();
        btn_verHistoriaClinica = new javax.swing.JButton();
        lbl_doctor = new javax.swing.JLabel();
        lbl_codigo = new javax.swing.JLabel();
        btn_cargarAtencion = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Atención");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Sección", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 12))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 310, 42));

        txt_fechaNaciminetoPaciente.setText("Fecha de nacimiento: ");
        jPanel1.add(txt_fechaNaciminetoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        txt_dniPaciente.setText("Dni:");
        jPanel1.add(txt_dniPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 20));

        txt_nombrePaciente.setText("Nombre:");
        jPanel1.add(txt_nombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 20));

        txt_telefonoPaciente.setText("Teléfono:");
        jPanel1.add(txt_telefonoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));

        txt_edadPaciente.setText("Edad:");
        jPanel1.add(txt_edadPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        txt_direccionPaciente.setText("Dirección:");
        jPanel1.add(txt_direccionPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        txt_generoPaciente.setText("Género: ");
        jPanel1.add(txt_generoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("INFORMACIÓN DEL PACIENTE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        CBX_SELECT_ESPEC.setBackground(new java.awt.Color(204, 255, 255));
        CBX_SELECT_ESPEC.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        CBX_SELECT_ESPEC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        CBX_SELECT_ESPEC.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Especialidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N
        jPanel1.add(CBX_SELECT_ESPEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 238, 50));

        TXTA_OBSERVACIONES.setColumns(20);
        TXTA_OBSERVACIONES.setRows(5);
        TXTA_OBSERVACIONES.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Observaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jScrollPane1.setViewportView(TXTA_OBSERVACIONES);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, 110));

        TXTA_DIAGNOSTICO.setColumns(20);
        TXTA_DIAGNOSTICO.setRows(5);
        TXTA_DIAGNOSTICO.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Diagnóstico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jScrollPane2.setViewportView(TXTA_DIAGNOSTICO);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 240, 110));

        TXTA_MOTIVO.setColumns(20);
        TXTA_MOTIVO.setRows(5);
        TXTA_MOTIVO.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Motivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jScrollPane3.setViewportView(TXTA_MOTIVO);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, 110));

        btn_modificarAtencion.setBackground(new java.awt.Color(0, 153, 153));
        btn_modificarAtencion.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_modificarAtencion.setText("MODIFICAR");
        jPanel1.add(btn_modificarAtencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 150, 30));

        btn_Eliminar.setBackground(new java.awt.Color(0, 153, 153));
        btn_Eliminar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_Eliminar.setText("ELIMINAR");
        jPanel1.add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 150, 30));

        btn_buscarPaciente.setBackground(new java.awt.Color(0, 153, 153));
        btn_buscarPaciente.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_buscarPaciente.setText("BUSCAR PACIENTE");
        jPanel1.add(btn_buscarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 220, 40));

        tbl_tablaAtencion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código atención", "Dni Paciente", "Fecha", "Especialidad", "Doctor", "Descripcion Atencion"
            }
        ));
        jScrollPane4.setViewportView(tbl_tablaAtencion);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 1020, 300));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("REGISTRO ATENCIÓN");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, 20));

        btn_agregarAtencion.setBackground(new java.awt.Color(0, 153, 153));
        btn_agregarAtencion.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_agregarAtencion.setText("AGREGAR");
        jPanel1.add(btn_agregarAtencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 150, 30));

        TXTA_TRATAMIENTO.setColumns(20);
        TXTA_TRATAMIENTO.setRows(5);
        TXTA_TRATAMIENTO.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tratamiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jScrollPane5.setViewportView(TXTA_TRATAMIENTO);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 240, 110));

        btn_limpiarAtencion.setBackground(new java.awt.Color(0, 153, 153));
        btn_limpiarAtencion.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_limpiarAtencion.setText("LIMPIAR");
        jPanel1.add(btn_limpiarAtencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 150, 30));

        btn_verHistoriaClinica.setBackground(new java.awt.Color(0, 153, 153));
        btn_verHistoriaClinica.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_verHistoriaClinica.setText("HISTORIA CLINICA");
        jPanel1.add(btn_verHistoriaClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 190, 40));

        lbl_doctor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_doctor.setText("Doctor:");
        jPanel1.add(lbl_doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 170, -1));

        lbl_codigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_codigo.setText("Codigo:");
        jPanel1.add(lbl_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 170, -1));

        btn_cargarAtencion.setBackground(new java.awt.Color(0, 153, 153));
        btn_cargarAtencion.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_cargarAtencion.setText("CARGAR");
        jPanel1.add(btn_cargarAtencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 370, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> CBX_SELECT_ESPEC;
    public javax.swing.JTextArea TXTA_DIAGNOSTICO;
    public javax.swing.JTextArea TXTA_MOTIVO;
    public javax.swing.JTextArea TXTA_OBSERVACIONES;
    public javax.swing.JTextArea TXTA_TRATAMIENTO;
    public javax.swing.JButton btn_Eliminar;
    public javax.swing.JButton btn_agregarAtencion;
    public javax.swing.JButton btn_buscarPaciente;
    public javax.swing.JButton btn_cargarAtencion;
    public javax.swing.JButton btn_limpiarAtencion;
    public javax.swing.JButton btn_modificarAtencion;
    public javax.swing.JButton btn_verHistoriaClinica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JLabel lbl_codigo;
    public javax.swing.JLabel lbl_doctor;
    public javax.swing.JTable tbl_tablaAtencion;
    public javax.swing.JLabel txt_direccionPaciente;
    public javax.swing.JLabel txt_dniPaciente;
    public javax.swing.JLabel txt_edadPaciente;
    public javax.swing.JLabel txt_fechaNaciminetoPaciente;
    public javax.swing.JLabel txt_generoPaciente;
    public javax.swing.JLabel txt_nombrePaciente;
    public javax.swing.JLabel txt_telefonoPaciente;
    // End of variables declaration//GEN-END:variables
}
